sudo: false
dist: trusty

language: php

addons:

php:
- 7.0
- hhvm

env:

lobal:
    - "FTP_USER=l3padmin_site_dalton"
    - "FTP_PASSWORD="
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://daltonmartins.medialab.ufg.br/web/wp-content/themes/tainacan/"
    
    
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

script:

notifications:
  email: false
