sudo: false
dist: trusty

language: php

addons:

php:
- 7.0
- hhvm

env:


after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD $URL"
    
    
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

script:

notifications:
  email: false
