sudo: false
dist: trusty

language: php

addons:

php:
- 7.0
- hhvm

env:

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

script:

notifications:
  email: false
