language: php

php:
- 7.1
- hhvm

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script: phpunit

after_success: curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD $URL

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - vendor
    
notifications:
  on_success: never
  on_failure: always
