sudo: false
dist: trusty

language: php

php:
- 7.0
- hhvm

after_success:

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

script:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD $URL"
    
notifications:
  email: false
